### ISSUE TITLE
Provide the zig-tls as a module rather than static library

### ISSUE THREAD

**Issue by Cloudef** [melonedo/zig-tls12#3]
Since this is a purely zig library that does not expose C api, exposing it as a zig module would make more sense.

**Comment by melonedo** [comment]
Can you elaborate on this a little? I am not sure what static library means here. Also, any PR to packaging is welcomed since I am new to zig.



---Original---
From: "Jari ***@***.***&gt;
Date: Sat, Jan 27, 2024 13:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [melonedo/zig-tls12] Provide the zig-tls as a module rather thanstatic library (Issue #3)




 
Since this is a purely zig library that does not expose C api, exposing it as a zig module would make more sense.

**Comment by Cloudef** [comment]
Pushed PR :)
